name: Build Launcher APK
on: [push]
jobs:
  build:
    # 22.04 सबसे तेज मिलता है (No Waiting)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # डिस्क स्पेस खाली करना (ताकि जगह कम न पड़े)
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      # Java 17 (API 33 के लिए जरूरी) + सारे टूल्स
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libltdl-dev libffi-dev libssl-dev autoconf autotools-dev unzip

      # Buildozer और Cython का सही वर्जन
      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33

      # APK बनाना (NDK 25b अपने आप डाउनलोड होगा)
      - name: Build APK
        run: |
          yes | buildozer android debug

      # APK अपलोड
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeoLauncher-Final
          path: bin/*.apk
          
