name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # हम यहाँ "ArtemSBulgakov" की जगह "Official Kivy Action" यूज़ करेंगे
      - name: Build with Buildozer
        uses: kivy/buildozer-action@v1.3.0
        with:
          repository_root: .
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: launcher-apk
          path: bin/*.apk
          
